### ISSUE TITLE
C:\Python27\lib\pkgutil.py:183: ImportWarning: Not importing directory

### ISSUE THREAD

**Issue by mad11971** [kaushalshetty/FeatureSelectionGA#5]
plz help to time run 
error 
C:\Python27\lib\site-packages\deap\tools\_hypervolume\pyhv.py:33: ImportWarning: Falling back to the python version of hypervolume module. Expect this to be very slow.
  "module. Expect this to be very slow.", ImportWarning)
C:\Python27\lib\pkgutil.py:183: ImportWarning: Not importing directory 'C:\Users\taha\AppData\Roaming\Python\Python27\site-packages\mpl_toolkits': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
C:\Python27\lib\pkgutil.py:183: ImportWarning: Not importing directory 'c:\users\taha\appdata\roaming\python\python27\site-packages\mpl_toolkits': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
C:\Python27\lib\pkgutil.py:183: ImportWarning: Not importing directory 'C:\Python27\lib\site-packages\google': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
C:\Python27\lib\pkgutil.py:183: ImportWarning: Not importing directory 'c:\python27\lib\site-packages\google': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
C:\Python27\lib\pkgutil.py:183: ImportWarning: Not importing directory 'C:\Python27\lib\site-packages\google\cloud': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
C:\Python27\lib\pkgutil.py:183: ImportWarning: Not importing directory 'C:\Python27\lib\site-packages\google\cloud\proto': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
C:\Python27\lib\pkgutil.py:183: ImportWarning: Not importing directory 'C:\Python27\lib\site-packages\google\cloud\proto\pubsub': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
C:\Python27\lib\pkgutil.py:183: ImportWarning: Not importing directory 'C:\Python27\lib\site-packages\google\cloud\proto\datastore': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
C:\Python27\lib\pkgutil.py:183: ImportWarning: Not importing directory 'C:\Python27\lib\site-packages\google\pubsub': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
C:\Python27\lib\pkgutil.py:183: ImportWarning: Not importing directory 'C:\Python27\lib\site-packages\google\logging': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
C:\Python27\lib\pkgutil.py:183: ImportWarning: Not importing directory 'C:\Python27\lib\site-packages\google\iam': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
C:\Python27\lib\pkgutil.py:183: ImportWarning: Not importing directory 'C:\Python27\lib\site-packages\google\cloud\logging': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
C:\Python27\lib\pkgutil.py:183: ImportWarning: Not importing directory 'C:\Python27\lib\site-packages\google\cloud\gapic': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
C:\Python27\lib\pkgutil.py:183: ImportWarning: Not importing directory 'C:\Python27\lib\site-packages\google\cloud\gapic\pubsub': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)

plz help tanks
plz exampl for run program send for me . tanks

**Comment by PuneethaPai** [comment]
Examples to use this package is shown in Readme file. Do refer them. Thanks
