### ISSUE TITLE
ModuleNotFoundError: No module named 'feature_selection_ga'

### ISSUE THREAD

**Issue by kurvaraviteja355** [kaushalshetty/FeatureSelectionGA#9]
I have installed DEAP even tough i am getting this error, Why am i getting this error?

**Comment by kaushalshetty** [comment]
It's not DEAP installation error. Have you cloned the repo?

**Comment by kurvaraviteja355** [comment]
Yes I have cloned the repo

**Comment by PuneethaPai** [comment]
@kurvaraviteja355 now this is made available as a python package. You can install using `pip install feature-selection-ga` and use it.

Do refer to examples in Readme file, which are updated to reflect the same.

Thanks
